# Generated by Django 4.2 on 2025-01-21 23:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=accounts.models.image_upload),
        ),
    ]
