# Generated by Django 4.2 on 2025-03-04 23:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(default='defaults/profile_pic/default-profile-pic.png', upload_to=accounts.models.image_upload),
        ),
    ]
