# Generated by Django 4.2 on 2025-01-20 13:05

import chats.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_account_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(upload_to=chats.models.group_image)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('max_member_no', models.IntegerField()),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_custom_group', to='accounts.account')),
                ('members', models.ManyToManyField(related_name='member_custom_group', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(null=True)),
                ('recipient', models.ManyToManyField(related_name='received_messages', to='accounts.account')),
                ('recipient_group', models.ManyToManyField(related_name='group_rec_messages', to='chats.customgroups')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='accounts.account')),
            ],
        ),
    ]
