# Generated by Django 4.2 on 2025-03-04 23:04

import chats.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_profile_picture'),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customgroups',
            name='profile_picture',
            field=models.ImageField(default='defaults/profile_pic/default-profile-pic.png', upload_to=chats.models.group_image),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.RemoveField(
            model_name='messages',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='recipient_group',
        ),
        migrations.AddField(
            model_name='messages',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account'),
        ),
        migrations.AddField(
            model_name='messages',
            name='recipient_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.customgroups'),
        ),
    ]
