# Generated by Django 4.2 on 2025-03-05 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_profile_picture'),
        ('chats', '0003_alter_messages_recipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_list', models.JSONField(default=list)),
                ('participant_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant1_convo', to='accounts.account')),
                ('participant_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant2_convo', to='accounts.account')),
            ],
        ),
    ]
