# Generated by Django 4.2 on 2025-03-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
