# Generated by Django 4.2 on 2025-03-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_conversation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='messages',
            field=models.ManyToManyField(to='chats.messages'),
        ),
    ]
