# Generated by Django 4.2 on 2025-03-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_conversation_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='message_list',
        ),
    ]
