# Generated by Django 4.2 on 2025-03-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_remove_conversation_message_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
