# Generated by Django 4.2 on 2025-06-20 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_messages_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroups',
            name='messages',
            field=models.ManyToManyField(to='chats.messages'),
        ),
        migrations.AddField(
            model_name='customgroups',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customgroups',
            name='max_member_no',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='messages',
            name='recipient_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recieving_groups', to='chats.customgroups'),
        ),
    ]
